stages:
  process_data:
    cmd: python src/process_data.py
    deps:
    - config/main.yaml
    - config/data
    - data/raw
    - src/process_data.py
    outs:
    - data/processed:
        persist: true
  train_model:
    cmd: python src/train_model.py
    deps:
    - config/main.yaml
    - config/data
    - config/model
    - data/raw
    - data/processed
    - src/train_model.py
    outs:
    - data/final:
        persist: true
    - models:
        persist: true
